name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Build
      run: |
        git clone git@github.com:hemlok/emotion-box.git
        yarn
        yarn build
